source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JHSpinner_Example', :exclusive => true do
  pod "JHSpinner", :path => "../"
end

target 'JHSpinner_Tests', :exclusive => true do
  pod "JHSpinner", :path => "../"

  
end
