source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JHSpinner_Example' do
  pod "JHSpinner", :path => "../"
end

target 'JHSpinner_Tests' do
  pod "JHSpinner", :path => "../"
end
